# Pandas使用练习

## 安装

In [4]:
# !pip install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple

In [1]:
import pandas as pd

In [10]:
# !pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple

In [10]:
import numpy as np

## 常用数据类型
- Series: 一维，带标签数组
- DataFrame: 二维，Series容器

### Series的使用总结

- 创建

In [2]:
# 通过list创建
ser_obj = pd.Series(range(10, 20))
print(ser_obj)
print(type(ser_obj))

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
<class 'pandas.core.series.Series'>


In [3]:
# 获取数据和索引
print(ser_obj.values)
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


In [5]:
# 通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


In [7]:
# 索引与数据的对应关系不被运算结果影响
print(ser_obj * 2)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64


In [8]:
print(ser_obj > 15)

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [ ]:
# 通过dict 构建series


In [11]:
# 通过dict 构建series
import string
t = pd.Series(np.arange(10), index=list(string.ascii_uppercase[:10]))
t

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int64

In [12]:
type(t)

pandas.core.series.Series

In [14]:
a = {string.ascii_uppercase[i]:i for i in range(10)}  #字典推导式创建字典
a

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9}

In [17]:
type(a)

dict

In [15]:
pd.Series(a)

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int64

In [16]:
pd.Series(a, index=list(string.ascii_uppercase[5:15]))

F    5.0
G    6.0
H    7.0
I    8.0
J    9.0
K    NaN
L    NaN
M    NaN
N    NaN
O    NaN
dtype: float64

- 切片和索引
    - 切片：直接传start end 或步长即可
    - 索引：一个的时候直接传入序号或者index，多个的时候传入序号或者index列表

In [18]:
t 

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int64

In [19]:
t[2:10:2]

C    2
E    4
G    6
I    8
dtype: int64

In [20]:
t[1]

1

In [21]:
t[[2,3,6]]

C    2
D    3
G    6
dtype: int64

In [22]:
t[t>4]

F    5
G    6
H    7
I    8
J    9
dtype: int64

In [23]:
t["F"]

5

In [27]:
t[["A","F","G"]]

A    0
F    5
G    6
dtype: int64

In [30]:
t.index, type(t.index)

(Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='object'),
 pandas.core.indexes.base.Index)

In [31]:
t.values, type(t.values)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

### DataFrame的使用总结

In [35]:
t = pd.DataFrame(np.arange(12).reshape((3,4)))
t

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [37]:
# help(pd.DataFrame)

In [54]:
df = pd.DataFrame(np.arange(12).reshape((
    3,4)),index=list(string.ascii_uppercase[:3]), columns=list(string.ascii_uppercase[-4:]))

In [56]:
df

W  X   Y   Z
A  0  1   2   3
B  4  5   6   7
C  8  9  10  11

- 基础属性

In [58]:
df.shape  # 行数、列数

(3, 4)

In [59]:
df.dtypes  # 列数据类型

W    int64
X    int64
Y    int64
Z    int64
dtype: object

In [60]:
df.ndim  # 数据维度

2

In [61]:
df.index # 行索引

Index(['A', 'B', 'C'], dtype='object')

In [62]:
df.columns # 列索引

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [63]:
df.values # 对象值，二维ndarray数组

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
df.info()  # 相关信息概览

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       3 non-null      int64
 1   X       3 non-null      int64
 2   Y       3 non-null      int64
 3   Z       3 non-null      int64
dtypes: int64(4)
memory usage: 120.0+ bytes


In [65]:
df.head(2)  # 显示前两行，默认显示5行

W  X  Y  Z
A  0  1  2  3
B  4  5  6  7

In [66]:
df.tail(1)  # 显示最后一行，默认显示5行

W  X   Y   Z
C  8  9  10  11

In [67]:
df.describe()  # 快速综合统计结果：计数，均值，标准差、最大值，四分位数，最小值 

W    X     Y     Z
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [70]:
df.loc["A","W"] #通过标签索引行数据

0

In [71]:
 df.loc["B", "Z"]

7

In [78]:
df.loc["B","Z"] = 100  # 修改数据
df

W  X   Y    Z
A  0  1   2    3
B  4  5   6  100
C  8  9  10   11

In [75]:
df.iloc[1:2,1:3]  # 通过位置获取行数据

X  Y
B  5  6

## 生成一段时间范围

In [79]:
pd.date_range(start="20220101",end="20221231")

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [82]:
pd.date_range(start="20220101",end="20221231",freq="BM")  # 每个月最后一个工作日

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-29',
               '2022-05-31', '2022-06-30', '2022-07-29', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-30'],
              dtype='datetime64[ns]', freq='BM')

In [81]:
pd.date_range(start="20220101",periods=10, freq="WOM-3FRI")

DatetimeIndex(['2022-01-21', '2022-02-18', '2022-03-18', '2022-04-15',
               '2022-05-20', '2022-06-17', '2022-07-15', '2022-08-19',
               '2022-09-16', '2022-10-21'],
              dtype='datetime64[ns]', freq='WOM-3FRI')

## 读取外部数据

- pd.read_csv
- pd.read_sql(sql_sentence, connection)